### ISSUE TITLE
Do you recommend using BRACKEN after Kraken?

### ISSUE THREAD

**Issue by wanglu2014** [biocore/tcga#25]
In the original Nature article, no BRACKEN was mentioned. I have find the BRACKEN docker in the github package, do you recommend using BRACKEN to classify genus? Or recommend using BRACKEN to classify species?

**Comment by gregpoore** [comment]
Hi there, thanks for your interest in our paper. We did not use Bracken in the original article and have since moved on to direct genome alignment methods like SHOGUN/Woltka (https://github.com/qiyunzhu/woltka), which provide more accurate taxonomy classification although at a higher computational cost. Additionally, since (to my knowledge) Bracken requires the original Kraken output files to re-estimate the taxonomy assignments, and since those TCGA Kraken files are collectively hundreds of terabytes of data, we are unfortunately unable to offer that ability to the public for this dataset. We considered using Bracken at one point, which is why the package is found in the github repo, but we ultimately decided against using it for this application based on the state of TCGA project at that time.

**Comment by wanglu2014** [comment]
Thank you for your timely reply!
